CREATE TABLE "properties" (
	"propertyId" serial PRIMARY KEY NOT NULL,
	"propertyName" varchar(100) NOT NULL,
	"category" varchar(100) NOT NULL,
	"propertyImage" text NOT NULL,
	"imageArr" text[] NOT NULL,
	"address" varchar(100) NOT NULL,
	"city" varchar(100) NOT NULL,
	"state" varchar(100) NOT NULL,
	"country" varchar(100) NOT NULL,
	"price" numeric(50) NOT NULL,
	"rating" smallint NOT NULL,
	"numberOfBathrooms" smallint NOT NULL,
	"numberOfguest" smallint NOT NULL,
	"numberOfBedrooms" smallint NOT NULL,
	"numberOfStudies" smallint NOT NULL,
	"hostName" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"amenties" text[] NOT NULL,
	"healthAndSafety" text[] NOT NULL,
	"houseRules" text[] NOT NULL,
	"propertyType" varchar NOT NULL,
	"is_cancelable" boolean NOT NULL
);
